<?php
$flash = $this->flashMessenger();
// $flash->setMessageOpenFormat('<div$s role="alert">
//     <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
//     </button>
//     <ul class="list-unstyled"><li>')
//     ->setMessageSeparatorString('</li><li>')
//     ->setMessageCloseStrong('</li></ul></div>');

//     echo $flash->render('error' . ['alert', 'alert-dismissable', 'alert-danger', 'fade', 'show']);
//     echo $flash->render('info' . ['alert', 'alert-dismissable', 'alert-info', 'fade', 'show']);
//     echo $flash->render('default' . ['alert', 'alert-dismissable', 'alert-warning', 'fade', 'show']);
//     echo $flash->render('success' . ['alert', 'alert-dismissable', 'alert-success', 'fade', 'show']);